# Appendix A - Status of Structures Assessed in the Field {-}

## Data-deficient Barriers {-}

```{r}
#| label: table-3
#| tbl-cap: "Table 3: Structures in Morice River watershed that have been assessed for fish passage for Pacific salmon and steelhead as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat values."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/DD_MORR.csv", check.names=FALSE)
ft <- flextable(data)
ft <- set_header_labels(
  ft,
    'barrier_id' = 'Barrier ID',
    'internal_name' = 'Site Name',
    'watershed_group_code' = 'Watershed Name',
    'structure_type' = 'Structure Type',
    'assessment_type_completed' = 'Assessment Step Completed',
    'next_steps' = 'Next Step',
    'notes' = 'Notes',
    'supporting_links' = 'Supporting Links'
)
ft <- format_flextable(ft)
ft
```

## Excluded Structures {-}

```{r}
#| label: table-4
#| tbl-cap: "Table 4: Structures in Morice River watershed that are excluded from further consideration in subsequent ranking and work planning because the structure is not present, is confirmed passable (e.g., bridge), or has no habitat upstream for Pacific salmon and steelhead."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/EX_MORR.csv", check.names=FALSE)
ft <- flextable(data)
ft <- set_header_labels(
  ft,
    'barrier_id' = 'Barrier ID',
    'internal_name' = 'Site Name',
    'watershed_group_code' = 'Watershed Name',
    'structure_type' = 'Structure Type',
    'reason_for_exclusion' = 'Reason for Exclusion',
    'reason' = 'Reason Details',
    'supporting_links' = 'Supporting Links'
)
ft <- format_flextable(ft)
ft
```
