
# Acknowledgements and References {-}

## Recommended Citation 

B. Rebellato, Office of the Wet’suwet’en, N. Mazany-Wright, F. Montgomery, and N. W. R. Lapointe. 2026. Morice River watershed connectivity restoration plan. Canadian Wildlife Federation. Ottawa, Ontario, Canada. 


## Acknowledgements {-}

CWF recognizes that the lands and waters that form the basis of this plan are the traditional unceded territory of the Wet’suwet’en peoples. Plan development and implementation was funded by the BC Salmon Restoration and Innovation Fund. Members of the Planning Team [(Appendix B)](content/appendix-b.qmd) are passionate about the conservation and restoration of freshwater ecosystems and the species they support, and contributed feedback, guidance, and knowledge. Accessibility models were inspired by fish-passage prioritization approaches developed by British Columbia’s Fish Passage Technical Working Group.  

## References {-}

Irvine, A. 2021. Bulkley River and Morice River Watershed Groups Fish Passage Restoration Planning 2020. Prepared by New Graph Environment on behalf of Society for Ecosystem Restoration in Northern BC for Habitat Conservation Trust Foundation – CAT21-6-288, B. C. Fish Passage Remediation Program, and Canadian Wildlife Federation. https://www.newgraphenvironment.com/fish_passage_bulkley_2020_reporting/  


Irvine, A., M. Wintersheidt, and L. Schick. 2022. Bulkley River and Morice River Watershed Groups Fish Passage Restoration Planning 2021. Prepared by New Graph Environment on behalf of Society for Ecosystem Restoration in Northern BC for Habitat Conservation Trust Foundation – CAT21-6-288. Prepared by New Graph Environment on behalf of Society for Ecosystem Restoration in Northern BC for Canadian Wildlife Federation, Habitat Conservation Trust Foundation – CAT23-6-288, B. C. Fish Passage Remediation Program, and B. C. Ministry of Transportation and Infrastructure. https://www.newgraphenvironment.com/fish_passage_skeena_2021_reporting/  


Irvine, A. and L. Schick. 2024. Skeena Watershed Fish Passage Restoration Planning 2023. Prepared by New Graph Environment on behalf of Society for Ecosystem Restoration in Northern BC for Habitat Conservation Trust Foundation – CAT23-6-288, B. C. Fish Passage Remediation Program, and B. C. Ministry of Transportation and Infrastructure. https://www.newgraphenvironment.com/fish_passage_skeena_2021_reporting/ 


Irvine, A. and L. Schick. 2025. Skeena Watershed Fish Passage Restoration Planning 2024. Prepared by New Graph Environment on behalf of Society for Ecosystem Restoration in Northern BC for Habitat Conservation Trust Foundation – CAT23-6-288, B. C. Fish Passage Remediation Program, and B. C. Ministry of Transportation and Infrastructure. https://www.newgraphenvironment.com/fish_passage_skeena_2021_reporting/ 


McCarthy, M., and A. Fernando. 2015. “2015 Inventory of High Priority Culverted Fish Passage Barriers in the Lower/Middle Skeena, Bulkley, Morice, and Babine River Watersheds.” 


Morgan, D. and L. Reese-Hansen. 2024. Bii Wenii Kwa restoration/recovery plan: draft summary plan (version 1.3.2). Prepared for DFO and the Bii Wenii Kwa recovery team by Don Morgan Consulting and B.C. Ministry of Water, Land and Resource Management. 28 pp. 


Smith, J. 2018. “Assessing Barriers to Fish Passage Within the Wet’suwet’en First Nation Traditional Territory.” 


[SSAF] Skeena Sustainability Assessment Forum. 2021. “Skeena Sustainability Assessment Forum’s State of the Value Report for Fish & Fish Habitat.” 


Wilson, T., and K. Rabnet. 2007. Fish Passage Assessment of Highway 16 and CN Rail in the Bulkley Watershed. https://data.skeenasalmon.info/dataset/fish-passage-assessment-highway-16-cn-rail-bulkley. 
